web_music_player/account/urls.py
from django.urls import path, include
from . import views

app_name = 'site_account'
urlpatterns = [
    # path('signup/', views.OwnSignupView.as_view(), name='signup'),
    path('signup/', views.register, name='signup'),
    path('login/', views.OwnLoginView.as_view(), name='login'),
    path('logout/', views.OwnLogoutView.as_view(), name='logout'),
    path('update/<int:pk>', views.OwnAccountUpdateView.as_view(), name='update'),
    path('password/', views.OwnPasswordChangeView.as_view(), name='password'),
    # path('password_change_done/', views.OwnPasswordChangeDoneView.as_view(), name='password_change_done'),
]

web_music_player/playlist/urls.py
from django.urls import path, include
from . import views

app_name = 'site_playlist'
urlpatterns = [
    path('<int:playlist_id>/', views.index, name='index'),
    path('getTracks/<int:playlist_id>/', views.get_track_ids, name='get_track_ids'),
    path('favourites/', views.update_favourites, name='update_favourites'),
    path('own/', views.get_user_playlists, name='get_user_playlists'),
]

web_music_player/user/urls.py
from django.urls import path, include
from . import views

app_name = 'site_user'
urlpatterns = [
    path('', views.index, name='index'),
    path('browse/', views.browse, name='browse'),
    path('activity/', views.activity, name='activity'),
]

web_music_player/web_music_player/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from account.views import OwnPasswordChangeDoneView



urlpatterns = [
    path('', include('user.urls', namespace='user')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('playlist/', include('playlist.urls', namespace='playlist')),
    path('track/', include('track.urls', namespace='track')),
    path('album/', include('album.urls', namespace='album')),
    path('artist/', include('artist.urls', namespace='artist')),
    path('password_change_done/', OwnPasswordChangeDoneView.as_view(), name='password_change_done'),
    path('admin-dashboard/', include('admin.urls')),
]


# ] + [
#     re_path(
#         r'^%s(?P<path>.*)$' % settings.STATIC_URL[1:], 
#         serve,
#         {
#         'document_root': os.path.join(
#             settings.BASE_DIR),
#         'show_indexes' : True})
# ] # remove ..staticfiles from INSTALLED_APPS too.

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_music_player/playlist/models.py
from django.db import models

web_music_player/playlist/forms.py
from django import forms
from user.models import Playlist

class ViewPlaylistForm(forms.ModelForm):

    class Meta:
        model = Playlist
        fields = ['name']
        widgets = {}

web_music_player/user/forms.py
from django import forms
from .models import Userbase, Profile

web_music_player/playlist/views.py
import logging
import json
from datetime import datetime, timezone
from typing import List

from django.db.models import Sum
from django.views import generic
from django.core import serializers
from django.http import JsonResponse, HttpResponse
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from .forms import ViewPlaylistForm
from user.models import Playlist, Userbase, Track

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.DEBUG)


@login_required
def update_favourites(request):
    data = json.loads(request.body.decode('utf-8'))
    curr_user = Userbase.objects.get(id=request.user.id)
    now = datetime.now(timezone.utc)
    track = Track.objects.get(id=data['track_id'])
    if request.method == 'POST':
        curr_user.favourites.add(track, through_defaults={'added_at': now})
        info = {'added': True}
    elif request.method == 'DELETE':
        curr_user.favourites.remove(track)
        info = {'removed': True}
    else:
        return 'HTTPNotAllowed'
    return JsonResponse(
        {**{'playlist': curr_user.get_full_name() + "'s Favourites",
            'track': track.title,
            'updated_by': curr_user.username,
            'success': True},
        **info}
    )

@login_required
def index(request, playlist_id):    
    "changing header is tricky when using generic views"

    curr_user = Userbase.objects.get(id=request.user.id)
    curr_playlist = Playlist.objects.get(id=playlist_id)
    if request.method == 'POST' or request.method == 'DELETE':
        data = json.loads(request.body.decode('utf-8'))
        now = datetime.now(timezone.utc)
        track = Track.objects.get(id=data['track_id'])

        if request.method == 'POST':
            curr_playlist.tracks.add(track, through_defaults={'added_at': now})
            info = {'added': True}
        elif request.method == 'DELETE':    
            curr_playlist.tracks.remove(track)
            info = {'removed': True}
    
        return JsonResponse({
            **{'playlist': curr_playlist.name,
                'updated_by': curr_user.username,
                'track': track.title,
                'success': True},
            **info
        })
    elif request.method == 'GET':
        user_playlists = get_user_playlists_obj(request)
        playlist_duration = curr_playlist.tracks.aggregate(
                     playlist_duration=Sum('duration'))['playlist_duration']
        context = {
            'current_playlist': curr_playlist,
            'playlist_duration': playlist_duration,
            'curr_user': curr_user,
            'playlists': user_playlists,
        }
        resp = render(request, 'user/playlist.html', context=context)
        resp["X-Frame-Options"] = 'SAMEORIGIN'
        return resp
    else:
        return 'HTTPNotAllowed'

@login_required
def get_track_ids(request, playlist_id):
    return JsonResponse([
        t.id for t in Playlist.objects.get(id=playlist_id).tracks.all()
    ], safe=False)

def get_user_playlists_obj(request) -> List['QuerySet']:
    curr_user = Userbase.objects.get(id=request.user.id)
    other_playlists = curr_user.playlists.all().order_by('-last_played_at')
    own_playlists = Playlist.objects \
                        .filter(owner__id=curr_user.id) \
                        .order_by('-last_played_at')

    return list(own_playlists) + list(other_playlists)
    
@login_required
def get_user_playlists(request):
    serialized = serializers.serialize('json', get_user_playlists_obj(request))
    return HttpResponse(content=serialized, content_type='application/json')

web_music_player/user/views.py
import logging
import json
from django.views import generic
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from .forms import ViewPlaylistForm
from .models import Playlist, Userbase, Artist, Album
from typing import Dict, List

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.DEBUG)

options_to_fields = {
    'artist_name': 'track__artist',
    'album_name': 'track__album',
    'date_added': 'added_at',
    'track_name': 'track__name',
}

@login_required
def index(request):
    context = {}
    resp = render(request, 'user/skeleton.html', context=context)
    return resp

@login_required
def get_tracks_in_playlist(playlist):
    playlist_order = playlist.sort_by
    return playlist.trackplaylists_set.all() \
                .order_by(options_to_fields[playlist_order])

@login_required
def browse(request):
    playlists = Playlist.objects.all()
    curr_user = Userbase.objects.get(id=request.user.id)
    
    categories: Dict[str, List['QuerySet']] = {}
    categories['Recently Played'] = Playlist.objects.filter(owner__id=curr_user.id) \
                                    .order_by('-last_played_at')
    categories['Top Playlists'] = playlists.order_by('-times_played')[:5]
    categories['Recommended Playlists'] = [
        p for p in playlists if p not in categories['Top Playlists']
    ]
    
    artists = {}
    artists['Featured Artists'] = Artist.objects.all()

    albums = {}
    albums['New Releases'] = Album.objects.all().order_by('-released_at')

    songs = {}
    songs['Music by genres'] = []
    songs['The 90s'] = []

    context = {
        'playlist_categories': categories,
        'album_categories': albums,
        'artist_categories': artists,
        'songs_categories': songs,
        'Favourite': curr_user.favourites.all(),
        'user_obj': curr_user,
    }

    resp = render(request, 'user/browse.html', context=context)
    resp["X-Frame-Options"] = 'SAMEORIGIN'
    return resp

@login_required
def activity(request):
    if request.method == 'POST':
        curr_user = Userbase.objects.get(id=request.user.id)
        data = json.loads(request.body.decode('utf-8'))
        info = {}
        leader = Userbase.object.get(id=int(data['id']))
        if data['type'] == 'follow':
            leader.followers.add(curr_user)
            info = {'added': True}
        elif data['type'] == 'unfollow':
            leader.followers.remove(curr_user)
            info = {'removed': True}
        return JsonResponse({
            **{'leader_id': leader.id,
            'follower_id': curr_user.id,
            'success': True},
            **info,
        })

web_music_player/user/templates/user/base.html
{% extends 'base.html' %}
{% load static %}

{% block inline_css %}
    <style >
        
        .aplayer .aplayer-list ol li.aplayer-list-light, .aplayer .aplayer-list ol li:hover {
            background-color: black !important;
        }
        .btn {
            cursor: pointer;
            color: white !important;
        }
        canvas {
            position: fixed;
            top: 0;
            left: 0;
            pointer-events: none;
            height: 100vh;
            width: 100vw;
        }
        
    </style>
{% endblock inline_css %}


{% block content %}
    <div class="main">
        <nav></nav>
        <div class="iframe-browse">
            {% block iframe %} {% endblock iframe %}
        </div>
        
        <div class="music-controller">
            <div id="3rd-p-player"></div>
        </div>

    </div>

    <canvas></canvas>
{% endblock content %}

web_music_player/user/templates/user/browse.html
{% extends 'user/base.html' %}
{% load static %}

{% block title %}
    Browse - Wave
{% endblock title %}

{% block external_css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'user/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fonts/ronet-Regular.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/cards.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'artist/css/artist.css' %}">
{% endblock external_css %}

{% block content %}
    
    <div class="main-grid">
        <aside class="">
            <a class="" href="{% url 'user:browse' %}">
                <div class="logo">
                    <img src="{% static 'user/imgs/logo.svg' %}">
                    <span id="app-name">Wave</span>
                </div>
            </a>
            <div class="sidebar-links" style="display: none">
                <div>
                    <a href="">
                        <i class="ri-home-6-fill"></i>
                        <span>Home</span>
                    </a>
                </div>
                <div>
                    <a href="">
                        <i class="ri-search-2-line"></i>
                        <span>Search</span>
                    </a>
                </div>
                <div>
                    <a href="">
                        <i class="ri-folder-music-line"></i>
                        <span>Your library</span>
                    </a>
                </div>
                <section class="playlists">
                    <br>
                    <h3>PLAYLISTS</h3>

                    <div>
                        <a href="">
                            <i class="ri-add-box-line"></i>
                            <span>Create playlist</span>
                        </a>
                    </div>
                    <div>
                        <a href="">
                            <i class="ri-heart-2-fill"></i>
                            <span>Fav songs</span>
                        </a>
                    </div>
                </section>
            </div>
        </aside>

        <div class="content">
            <header class="sticky-nav">
                <div class="tabs" style="visibility: hidden;">
                    <a href="#">Playlists</a>
                    <a href="#">Artists</a>
                    <a href="#">Albums</a>
                </div>
                
                <div class="btn account-dropdown">
                    <img class="user-profile-pic rounded-circle" src="{{ user_obj.profile_pic.url }}">
                    <small class="username">{{ user.username }}</small>
                    <a href="#" class="more-account">
                        <i class="ri-arrow-down-s-fill"></i>
                        <div class="account">
                            <p>
                                <a href="{% url 'account:update' user.id %}" target="_blank">Account</a>
                                <i class="ri-external-link-line"></i>
                            </p>
                            <p>
                                <span id="logout">Log out</span>
                            </p>
                        </div>
                    </a>
                    <span>
                    </span>
                </div>
            </header>

            <div class="browse">
                <div>
                    {% include 'playlist/playlist_cards.html' with playlist_categories=playlist_categories only %}
                </div>

                <div>
                    {% include 'album/album_cards.html' with album_categories=album_categories only %}
                </div>

                <div>
                    {% include 'artist/artist_cards.html' with artist_categories=artist_categories only %}
                </div>
            </div>        
        </div>
    </div>

{% endblock content %}

{% block bottom_js %}
    <script src="{% static 'js/utils.js' %}"></script>
    <script>
        // window.addEventListener('message', (event) => {
        //     if (event.origin !== 'http://127.0.0.1:8000') return
        //     console.log('data from parent window :', event.data)
        // })
        // const cards = document.querySelectorAll('.my-card .cover-this')
        // for (let card of cards) {
        //     const img = new Image();
        //     img.src = `/static/user/imgs/${randomInt(1, 30)}.jfif`
        //     card.prepend(img)
        // }
        
        // redirect the parent document to logout. else it will appear on iframe.
        document.getElementById('logout').addEventListener('click', () => {
            parent.location.href = '/account/logout/'
        })

        // show/hide account and logout buttons
        const accLink = document.querySelector('.account-dropdown')
        const arrow = document.querySelector('.more-account')
        const accountDropdown = document.querySelector('.account')
        accLink.addEventListener('click', () => {
            const added = toggleClass(arrow, 'flip', 'unflip') 
            if (added === 'flip') {
                accountDropdown.style.display = 'block'
            }
            else {
                accountDropdown.style.display = 'none'
            }
        })

        /*// given playlistid, artistid, albumid; fetch and queue the tracks
        function request(url, id) {            
            fetch(url + id + '/', {
                method: 'GET',
            }).then(resp => resp.json())
                .then(trackIds => {
                    const tracks = []
                    trackIds.forEach((id) => {
                        tracks.push({'id': id})
                    })
                    window.parent.postMessage({
                        type: 'queueTracks',
                        tracks: tracks,
                        clearQueue: true,
                    }, 'http://127.0.0.1:8000')
                })
            
        }

        // play the playlist, album or artists tracks
        const playPlaylistBtns = document.querySelectorAll('.hover-play-card')
        playPlaylistBtns.forEach((btn) => {
            btn.addEventListener('click', (event) => {
                event.preventDefault()
                const playlistId = btn.dataset.playlistId
                const artistId = btn.dataset.artistId
                const albumId = btn.dataset.albumId
                if (playlistId) {
                    request('/playlist/getTracks/', playlistId)
                }
                else if (artistId) {
                    request('/artist/getTracks/', artistId)
                }
                else if (albumId) {
                    request('/album/getTracks/', albumId)
                }
            })
        })*/

    </script>
{% endblock bottom_js %}

web_music_player/user/templates/user/playlist.html
{% extends 'user/base.html' %}
{% load static %}
{% load sec_to_hhmmss %}

{% block title %}
    Playlist - Wave
{% endblock title %}

{% block external_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'playlist/css/playlist.css' %}">
{% endblock external_css %}

{% block content %}
    <div class="playlist-grid">
        <header class="playlist-info">
            <img class="header-img" src="{% static 'user/imgs/3.jfif' %}">
            <div class="info">  
                <p>PLAYLIST</p>
                <h1 id="playlist-name">{{ current_playlist.name }}</h1>
                <p>{{ current_playlist.description }}</p>
                <div>
                    <span>{{ current_playlist.owner.all|join:", " }}</span>
                    <ul>
                        <li>{{ current_playlist.userbase_set.all|length }} likes</li>
                        <li>Duration: {{ playlist_duration|sec_to_hhmmss }}</li>
                    </ul>
                </div>
            </div>
        </header>
        <div class="shortcuts">
            <span class="btn play-playlist ri-play-circle-fill"></span>
            <span class="btn heart-playlist ri-heart-line"></span>
            <span class="btn">...</span>
        </div>
        <div class="playlist-add display-none">
            {% include 'playlist/add_to_playlist_form.html' with playlists=playlists csrf_token=csrf_token only %}
        </div>
        <div class="tracks-list">
            <ul class="tracks">
                <li class="header-row">
                    <span class="index" id="track-num">#</span>
                    <span>Title</span>
                    <span class="queue-this">&nbsp;</span>
                    <span class="playlist-this">&nbsp;</span>
                    <span class="album">Album</span>
                    <span class="date-added">Date Added</span>
                    <span class="heart">&nbsp;</span>
                    <span class="track-duration">Duration</span>
                </li>
                {% for track in current_playlist.tracks.all %}
                    <li class="" data-track-id="{{ track.id }}">
                        <div class="index">
                            <span>{{ forloop.counter }}</span>
                            <i class="hover btn play-this ri-play-circle-fill"></i>
                        </div>
                        <div class="track-artist">
                            
                            <img src="/static/user/imgs/34.jfif">
                            <div class="">
                                <span>{{ track.title }}</span>
                                {% with main_artist=track.artist.all|first %}
                                    <span>
                                        <a href="{% url 'artist:index' main_artist.id %}">{{ main_artist.get_full_name }}</a>
                                    </span>
                                {% endwith %}
                            </div>
                        </div>
                        <span class="hidden btn ri-add-line queue-this" title="Add to Queue"></span>
                        <span class="hidden btn ri-play-list-add-line playlist-this" title="Add to Playlist"></span>
                        <span class="album" aria-label="album">
                            <a href="{% url 'album:index' track.album.id %}">{{ track.album.title }}</a>
                        </span>
                        <span class="date-added" aria-label="date-added">{{ track.created_at|date:"M d, Y" }}</span>
                        {% if track in curr_user.favourites.all %}
                            <span class="btn heart ri-heart-3-fill"></span>
                        {% else %}
                            <span class="btn heart ri-heart-3-line"></span>
                        {% endif %}
                        <span class="track-duration" aria-label="track-duration">{{ track.duration|sec_to_hhmmss }}</span>
                    </li>
                
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock content %}

{% block bottom_js %}
    <script src="{% static 'playlist/js/playlist.js' %}"></script>
{% endblock bottom_js %}

web_music_player/user/templates/user/skeleton.html
{% extends 'user/base.html' %}
{% load static %}

{% block title %}
    Home - Wave
{% endblock title %}

{% block external_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'user/css/APlayer.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/css/style.css' %}">
{% endblock external_css %}

{% block top_js %}
    <script src="{% static 'user/js/APlayer.min.js' %}"></script>
    <script type="module" src="{% static 'user/js/player.js' %}"></script>
{% endblock top_js %}

{% block iframe %}
    <iframe src="{% url 'user:browse' %}"></iframe>
{% endblock iframe %}